apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: user-mgo
  name: user-mgo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: user-mgo
    spec:
      containers:
      - image: mongo
        name: user-mgo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /mgo-user/data/db
      volumes:
        - name: mongo-persistent-storage
          awsElasticBlockStore:
            volumeID: vol-08a31207892984af9
            fsType: ext4
